### ISSUE TITLE
Can't build due to path referencing /home/Tobias-Fischer

### ISSUE THREAD

**Issue by kmod** [conda-forge/pyqt-feedstock#108]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

@Tobias-Fischer Building this feedstock results in the following error:

```
[snip]
g++ -Wl,--version-script=QtWidgets.exp -Wl,-O1 -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/pyqt_split_1648068148586/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
placehold_placehold_/lib -shared -o libQtWidgets.so sipQtWidgetsQAbstractButton.o sipQtWidgetsQAbstractGraphicsShapeItem.o sipQtWidgetsQAbstractItemDelegate.o sipQtWidgetsQAbstractItemView.o sipQtWidgetsQAbstractItemViewEditTriggers.o sipQtWidgetsQAbstractScrollArea.o sipQtWidgetsQAbstractSli
der.o sipQtWidgetsQAbstractSpinBox.o sipQtWidgetsQAbstractSpinBoxStepEnabled.o sipQtWidgetsQAction.o sipQtWidgetsQActionGroup.o sipQtWidgetsQApplication.o sipQtWidgetsQBoxLayout.o sipQtWidgetsQButtonGroup.o sipQtWidgetsQCalendarWidget.o sipQtWidgetsQCheckBox.o sipQtWidgetsQColorDialog.o sipQtWidgetsQColorDialogColorDialogOptions.o sipQtWidgetsQColumnView.o sipQtWidgetsQComboBox.o sipQtWidgetsQCommandLinkButton.o sipQtWidgetsQCommonStyle.o sipQtWidgetsQCompleter.o sipQtWidgetsQDataWidgetMapper.o sipQtWidgetsQDateEdit.o sipQtWidgetsQDateTimeEdit.o sipQtWidgetsQDateTimeEditSections.o sipQtWidgetsQDesktopWidget.o sipQtWidgetsQDial.o sipQtWidgetsQDialog.o sipQtWidgetsQDialogButtonBox.o sipQtWidgetsQDialogButtonBoxStandardButtons.o sipQtWidgetsQDirModel.o sipQtWidgetsQDockWidget.o sipQtWidgetsQDockWidgetDockWidgetFeatures.o sipQtWidgetsQDoubleSpinBox.o sipQtWidgetsQErrorMessage.o sipQtWidgetsQFileDialog.o sipQtWidgetsQFileDialogOptions.o sipQtWidgetsQFileIconProvider.o sipQtWidgetsQFileIconProviderOptions.o sipQtWidgetsQFileSystemModel.o sipQtWidgetsQFocusFrame.o sipQtWidgetsQFontComboBox.o sipQtWidgetsQFontComboBoxFontFilters.o sipQtWidgetsQFontDialog.o sipQtWidgetsQFontDialogFontDialogOptions.o sipQtWidgetsQFormLayout.o sipQtWidgetsQFormLayoutTakeRowResult.o sipQtWidgetsQFrame.o sipQtWidgetsQGesture.o sipQtWidgetsQGestureEvent.o sipQtWidgetsQGestureRecognizer.o sipQtWidgetsQGestureRecognizerResult.o sipQtWidgetsQGraphicsAnchor.o sipQtWidgetsQGraphicsAnchorLayout.o sipQtWidgetsQGraphicsBlurEffect.o sipQtWidgetsQGraphicsBlurEffectBlurHints.o sipQtWidgetsQGraphicsColorizeEffect.o sipQtWidgetsQGraphicsDropShadowEffect.o sipQtWidgetsQGraphicsEffect.o sipQtWidgetsQGraphicsEffectChangeFlags.o sipQtWidgetsQGraphicsEllipseItem.o sipQtWidgetsQGraphicsGridLayout.o sipQtWidgetsQGraphicsItem.o sipQtWidgetsQGraphicsItemGraphicsItemFlags.o sipQtWidgetsQGraphicsItemGroup.o sipQtWidgetsQGraphicsLayout.o sipQtWidgetsQGraphicsLayoutItem.o sipQtWidgetsQGraphicsLineItem.o sipQtWidgetsQGraphicsLinearLayout.o sipQtWidgetsQGraphicsObject.o sipQtWidgetsQGraphicsOpacityEffect.o sipQtWidgetsQGraphicsPathItem.o sipQtWidgetsQGraphicsPixmapItem.o sipQtWidgetsQGraphicsPolygonItem.o sipQtWidgetsQGraphicsProxyWidget.o sipQtWidgetsQGraphicsRectItem.o sipQtWidgetsQGraphicsRotation.o sipQtWidgetsQGraphicsScale.o sipQtWidgetsQGraphicsScene.o sipQtWidgetsQGraphicsSceneContextMenuEvent.o sipQtWidgetsQGraphicsSceneDragDropEvent.o sipQtWidgetsQGraphicsSceneEvent.o sipQtWidgetsQGraphicsSceneHelpEvent.o sipQtWidgetsQGraphicsSceneHoverEvent.o sipQtWidgetsQGraphicsSceneMouseEvent.o sipQtWidgetsQGraphicsSceneMoveEvent.o sipQtWidgetsQGraphicsSceneResizeEvent.o sipQtWidgetsQGraphicsSceneSceneLayers.o sipQtWidgetsQGraphicsSceneWheelEvent.o sipQtWidgetsQGraphicsSimpleTextItem.o sipQtWidgetsQGraphicsTextItem.o sipQtWidgetsQGraphicsTransform.o sipQtWidgetsQGraphicsView.o sipQtWidgetsQGraphicsViewCacheMode.o sipQtWidgetsQGraphicsViewOptimizationFlags.o sipQtWidgetsQGraphicsWidget.o sipQtWidgetsQGridLayout.o sipQtWidgetsQGroupBox.o sipQtWidgetsQHBoxLayout.o sipQtWidgetsQHeaderView.o sipQtWidgetsQInputDialog.o sipQtWidgetsQInputDialogInputDialogOptions.o sipQtWidgetsQItemDelegate.o sipQtWidgetsQItemEditorCreatorBase.o sipQtWidgetsQItemEditorFactory.o sipQtWidgetsQKeyEventTransition.o sipQtWidgetsQKeySequenceEdit.o sipQtWidgetsQLCDNumber.o sipQtWidgetsQLabel.o sipQtWidgetsQLayout.o sipQtWidgetsQLayoutItem.o sipQtWidgetsQLineEdit.o sipQtWidgetsQList0100QRectF.o sipQtWidgetsQList0100QTableWidgetSelectionRange.o sipQtWidgetsQList0100QTextEditExtraSelection.o sipQtWidgetsQList0100QWizardWizardButton.o sipQtWidgetsQList0101QAbstractButton.o sipQtWidgetsQList0101QAction.o sipQtWidgetsQList0101QDockWidget.o sipQtWidgetsQList0101QGesture.o sipQtWidgetsQList0101QGraphicsItem.o sipQtWidgetsQList0101QGraphicsTransform.o sipQtWidgetsQList0101QGraphicsView.o sipQtWidgetsQList0101QGraphicsWidget.o sipQtWidgetsQList0101QListWidgetItem.o sipQtWidgetsQList0101QMdiSubWindow.o sipQtWidgetsQList0101QScroller.o sipQtWidgetsQList0101QTableWidgetItem.o sipQtWidgetsQList0101QTreeWidgetItem.o sipQtWidgetsQList0101QUndoStack.o sipQtWidgetsQList0101QWidget.o sipQtWidgetsQListView.o sipQtWidgetsQListWidget.o sipQtWidgetsQListWidgetItem.o sipQtWidgetsQMainWindow.o sipQtWidgetsQMainWindowDockOptions.o sipQtWidgetsQMap0100QDate0100QTextCharFormat.o sipQtWidgetsQMdiArea.o sipQtWidgetsQMdiAreaAreaOptions.o sipQtWidgetsQMdiSubWindow.o sipQtWidgetsQMdiSubWindowSubWindowOptions.o sipQtWidgetsQMenu.o sipQtWidgetsQMenuBar.o sipQtWidgetsQMessageBox.o sipQtWidgetsQMessageBoxStandardButtons.o sipQtWidgetsQMouseEventTransition.o sipQtWidgetsQOpenGLWidget.o sipQtWidgetsQPanGesture.o sipQtWidgetsQPinchGesture.o sipQtWidgetsQPinchGestureChangeFlags.o sipQtWidgetsQPlainTextDocumentLayout.o sipQtWidgetsQPlainTextEdit.o sipQtWidgetsQProgressBar.o sipQtWidgetsQProgressDialog.o sipQtWidgetsQProxyStyle.o sipQtWidgetsQPushButton.o sipQtWidgetsQRadioButton.o sipQtWidgetsQRubberBand.o sipQtWidgetsQScrollArea.o sipQtWidgetsQScrollBar.o sipQtWidgetsQScroller.o sipQtWidgetsQScrollerProperties.o sipQtWidgetsQShortcut.o sipQtWidgetsQSizeGrip.o sipQtWidgetsQSizePolicy.o sipQtWidgetsQSizePolicyControlTypes.o sipQtWidgetsQSlider.o sipQtWidgetsQSpacerItem.o sipQtWidgetsQSpinBox.o sipQtWidgetsQSplashScreen.o sipQtWidgetsQSplitter.o sipQtWidgetsQSplitterHandle.o sipQtWidgetsQStackedLayout.o sipQtWidgetsQStackedWidget.o sipQtWidgetsQStatusBar.o sipQtWidgetsQStyle.o sipQtWidgetsQStyleFactory.o sipQtWidgetsQStyleHintReturn.o sipQtWidgetsQStyleHintReturnMask.o sipQtWidgetsQStyleHintReturnVariant.o sipQtWidgetsQStyleOption.o sipQtWidgetsQStyleOptionButton.o sipQtWidgetsQStyleOptionButtonButtonFeatures.o sipQtWidgetsQStyleOptionComboBox.o sipQtWidgetsQStyleOptionComplex.o sipQtWidgetsQStyleOptionDockWidget.o sipQtWidgetsQStyleOptionFocusRect.o sipQtWidgetsQStyleOptionFrame.o sipQtWidgetsQStyleOptionFrameFrameFeatures.o sipQtWidgetsQStyleOptionGraphicsItem.o sipQtWidgetsQStyleOptionGroupBox.o sipQtWidgetsQStyleOptionHeader.o sipQtWidgetsQStyleOptionMenuItem.o sipQtWidgetsQStyleOptionProgressBar.o sipQtWidgetsQStyleOptionRubberBand.o sipQtWidgetsQStyleOptionSizeGrip.o sipQtWidgetsQStyleOptionSlider.o sipQtWidgetsQStyleOptionSpinBox.o sipQtWidgetsQStyleOptionTab.o sipQtWidgetsQStyleOptionTabBarBase.o sipQtWidgetsQStyleOptionTabCornerWidgets.o sipQtWidgetsQStyleOptionTabTabFeatures.o sipQtWidgetsQStyleOptionTabWidgetFrame.o sipQtWidgetsQStyleOptionTitleBar.o sipQtWidgetsQStyleOptionToolBar.o sipQtWidgetsQStyleOptionToolBarToolBarFeatures.o sipQtWidgetsQStyleOptionToolBox.o sipQtWidgetsQStyleOptionToolButton.o sipQtWidgetsQStyleOptionToolButtonToolButtonFeatures.o sipQtWidgetsQStyleOptionViewItem.o sipQtWidgetsQStyleOptionViewItemViewItemFeatures.o sipQtWidgetsQStylePainter.o sipQtWidgetsQStyleState.o sipQtWidgetsQStyleSubControls.o sipQtWidgetsQStyledItemDelegate.o sipQtWidgetsQSwipeGesture.o sipQtWidgetsQSystemTrayIcon.o sipQtWidgetsQTabBar.o sipQtWidgetsQTabWidget.o sipQtWidgetsQTableView.o sipQtWidgetsQTableWidget.o sipQtWidgetsQTableWidgetItem.o sipQtWidgetsQTableWidgetSelectionRange.o sipQtWidgetsQTapAndHoldGesture.o sipQtWidgetsQTapGesture.o sipQtWidgetsQTextBrowser.o sipQtWidgetsQTextEdit.o sipQtWidgetsQTextEditAutoFormatting.o sipQtWidgetsQTextEditExtraSelection.o sipQtWidgetsQTimeEdit.o sipQtWidgetsQToolBar.o sipQtWidgetsQToolBox.o sipQtWidgetsQToolButton.o sipQtWidgetsQToolTip.o sipQtWidgetsQTreeView.o sipQtWidgetsQTreeWidget.o sipQtWidgetsQTreeWidgetItem.o sipQtWidgetsQTreeWidgetItemIterator.o sipQtWidgetsQTreeWidgetItemIteratorIteratorFlags.o sipQtWidgetsQUndoCommand.o sipQtWidgetsQUndoGroup.o sipQtWidgetsQUndoStack.o sipQtWidgetsQUndoView.o sipQtWidgetsQVBoxLayout.o sipQtWidgetsQWhatsThis.o sipQtWidgetsQWidget.o sipQtWidgetsQWidgetAction.o sipQtWidgetsQWidgetItem.o sipQtWidgetsQWidgetRenderFlags.o sipQtWidgetsQWizard.o sipQtWidgetsQWizardPage.o sipQtWidgetsQWizardWizardOptions.o sipQtWidgetscmodule.o qpywidgets_chimera_helpers.o qpywidgets_post_init.o  /home/conda/feedstock_root/build_artifacts/pyqt_split_1648068148586/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libQt5Widgets.so /home/conda/feedstock_root/build_artifacts/pyqt_split_1648068148586/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libQt5Gui.so /home/conda/feedstock_root/build_artifacts/pyqt_split_1648068148586/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libQt5Core.so /home/Tobias-Fischer/mambaforge/conda-bld/qt_1642368272551/_build_env/bin/../aarch64-conda-linux-gnu/sysroot/usr/lib64/libGL.so -lpthread
g++: error: /home/Tobias-Fischer/mambaforge/conda-bld/qt_1642368272551/_build_env/bin/../aarch64-conda-linux-gnu/sysroot/usr/lib64/libGL.so: No such file or directory
make[1]: *** [Makefile:1023: libQtWidgets.so] Error 1
make[1]: Leaving directory '/home/conda/feedstock_root/build_artifacts/pyqt_split_1648068148586/work/pyqt5/QtWidgets'
make: *** [Makefile:79: sub-QtWidgets-make_first-ordered] Error 2
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 239, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 211, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2371, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 1616, in bundle_conda
    utils.check_call_env(interpreter_and_args + [dest_file],
  File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/usr/bin/bash', '-e', '/home/conda/feedstock_root/build_artifacts/pyqt_split_1648068148586/work/build-pyqt.sh']' returned non-zero exit status 2.
valid configs are {'osx_64_python3.7.____cpython', 'osx_64_python3.8.____cpython', 'linux_aarch64_python3.7.____cpython', 'win_64_python3.8.____cpython', 'linux_aarch64_python3.9.____cpython', 'win_64_python3.10.____cpython', 'linux_aarch64_python3.10.____cpython', 'win_64_python3.9.____cpython', 'win_64_python3.7.____cpython', 'linux_64_python3.7.____cpython', 'linux_64_python3.9.____cpython', 'linux_64_python3.8.____cpython', 'osx_64_python3.10.____cpython', 'linux_64_python3.10.____cpython', 'osx_64_python3.9.____cpython', 'linux-pyston', 'linux_aarch64_python3.8.____cpython'}
```

I don't see any references to the "Tobias-Fischer" string in this feedstock so it might also be an issue with a dependency?

I didn't do any debugging since I figured you might know quickly what this is about, but I can look more into it if it would help.

### Installed packages

```shell
using build_locally.py
```

### Environment info

```shell
using build_locally.py on an aarch64 machine
```

**Comment by Tobias-Fischer** [comment]
This is quite likely because of https://github.com/conda-forge/qt-feedstock/issues/201

It needs fixing in the qt feedstock. Hopefully we will soon migrate to qt 5.15 where this problem (again hopefully) won't be present anymore.

**Comment by kmod** [comment]
Ah ok, makes sense. I was able to get the feedstock to build by changing the pinning to point to an older qt build ("5.12.9 *_4" instead of ">=5.12.9"), thanks for the help!
