### ISSUE TITLE
No module named 'PyQt5.QtWebEngineWidgets'

### ISSUE THREAD

**Issue by jschueller** [conda-forge/pyqt-feedstock#24]
I still cannot run orange3 because of this missing import on linux/py36:
```
$ PYTHONPATH=~/miniconda/lib/python3.6/site-packages/ PATH=~/miniconda/bin/:$PATH orange-canvas 
3
Traceback (most recent call last):
  File "/home/schueller/miniconda/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 26, in <module>
    from AnyQt.QtWebEngineWidgets import QWebEngineView
  File "/home/schueller/miniconda/lib/python3.6/site-packages/AnyQt/QtWebEngineWidgets.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import *
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/schueller/miniconda/bin/orange-canvas", line 4, in <module>
    import Orange.canvas.__main__
  File "/home/schueller/miniconda/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 26, in <module>
    from Orange.canvas.application.canvasmain import CanvasMainWindow
  File "/home/schueller/miniconda/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 29, in <module>
    from AnyQt.QtWebKitWidgets import QWebView
ImportError: cannot import name 'QWebView'
```

**Comment by ccordoba12** [comment]
QtWebEngineWidgets are not provided by Qt5 conda and conda-forge packages on Linux, only QtWebKitWidgets.

AnyQt needs to shim both namespaces, as qtpy does for Spyder.

So please raise the issue with them instead of here.
